### ISSUE TITLE
Use URL to redirect to Discord invite

### ISSUE THREAD

**Issue by robbai** [RLBot/rlbot.github.io#38]
As suggested by Skyborg:
"We could instead use the website to redirect `rlbot.org/discord` to the normal [Discord invite] link"
Message link for those that can view it: [from Skyborg](https://discordapp.com/channels/348658686962696195/602759889080811521/741650906264633366)

**Comment by tarehart** [comment]
It's a good suggestion. For more context: Although we have a discord vanity url available to us, they're problematic because they expire https://support.discord.com/hc/en-us/community/posts/360055651351-Level-3-Vanity-URL-Stability

I may do a subdomain like discord.rlbot.org so the redirect can be done easily with DNS

**Comment by tarehart** [comment]
http://discord.rlbot.org is now live.

These do *not* work, but I don't think it's a problem:
- https://discord.rlbot.org
- http://www.discord.rlbot.org
